typography_spectrum: 0.13142
color:
  brandColors:
    - '#000000'
    - '#efefef'
    - '#595554'
    - '#cd0021'
    - '#f3575b'
  brandStrength: 0.3125
  lightness: 0.3584584218915552
  saturation: 0.5625
  rhythmicContrast: 0.1820656112395227
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: testingthegrid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ze zijn live hoor
description: oh wat cool
purpose: []
