name: testingthegrid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13142
title: Testing the Don
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#efefef'
    - '#595554'
    - '#cd0021'
    - '#f3575b'
  brandStrength: 0.4375
  lightness: 0.3584584218915552
  saturation: 0.5625
  rhythmicContrast: 0.1820656112395227
purpose: []
